#!/bin/sh

case "$1" in
    start)
        /usr/bin/r1-ssh-control start
        ;;
    stop)
        /usr/bin/r1-ssh-control stop
        ;;
    restart)
        /usr/bin/r1-ssh-control stop
        /usr/bin/r1-ssh-control start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac
